name: New Victim
description: Report a new victim to be added to the registry
title: "[New Victim]: "
labels: ["victim", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please verify that this person is not already in the registry.
  - type: input
    id: name
    attributes:
      label: Name (Latin)
    validations:
      required: true
  - type: input
    id: name_native
    attributes:
      label: Name (Native/Persian)
  - type: input
    id: date
    attributes:
      label: Date of Incident/Death
      placeholder: YYYY-MM-DD
  - type: input
    id: location
    attributes:
      label: Location (City, Province)
  - type: textarea
    id: sources
    attributes:
      label: Sources / Evidence
      description: Provide links to reliable sources (news, videos, social media).
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: details
